version: '3.5'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: "${IAM_ACCOUNT}.dkr.ecr.ap-southeast-2.amazonaws.com/${APPSVC_NAME:-iphone-search}:${APPSVC_VERSION:-latest}"